name: diplomacy
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.2 <3.0.0'


dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.1.1
  googleapis: ^6.0.0
  googleapis_auth: ^1.2.0

  jaguar_jwt: ^3.0.0
  
  # dart_jsonwebtoken:
  #   git:
  #     url: git@github.com:WillHensel/dart_jsonwebtoken.git
  #     ref: google-support

  http: ^0.13.4

#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
