name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subsito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - run: flutter pub get
      - run: flutter test
